language: node_js
node_js: node
script:
  - npm run tsc

deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
      repo: calculemuscode/oli-widgets
    email: rob@calculem.us
    api_key:
      secure: mEHWItZUPm79AwhXQfcn3cqRr6zxJ8NAcjANVfVCJqS7Croa9CidxZPycj8VhzVEzCbyJEVmh0BKYY8t5EnpjNEBT3jppQqPvAH6LS8HPOMJDHHJVonRMX3EWajprwqyKNc0Bgmgl7xTHHLPNKgnG8jiOWyljWN0zXSnVhmxZ+0+HUtQCJwXgH1WCRTT8fCBkeWSu5Da5bzTSt/QSUs/0jNeXRH+4sMCWHuxZSP2HTwhnc4JnCPz151eni51Qa8AlTZIO413wevzaZerrDoP9VeR+Jts/ka7p6j5YGKLxeAXjRxseZ8iaytIXmSzZGu9VNf4TPazs99VedYsyfAvDVfh0TchpfqOTt1Gp3Xxppx12O0a21xpR7oxV1eDaJjNE8tHXq78v18trta6MD95MJvwSg6WzjphpVyUkS/RtyQjvRrJa8yz5dzrUlDiXDWE1haSeC7IkMAsE0okL/C/JqUhTauWdruuzIymKYd9L7vQ5KERNxoqtl5rmtxgN26iysUTSflM5KK6P2aBl+WzYFfAyurntwCTSPC9Zs7ipFqD2UD86StK9T9V/bHCpsT1f3rjr6z0V5sKCk0g8gvua8BpZwR5sH6/AKAIFhX10gXHmgWHKyLS6ipSoKwuEDywmqQC3Z9mYmsu8fJX+fspStojnh4uwjLcAJhSyJlMys0=
