language: node_js
node_js: node
script:
- npm run tsc
deploy:
  - provider: npm
    skip_cleanup: true
    on:
      tags: true
      repo: calculemuscode/oli-widgets
    email: rob@calculem.us
    api_key:
      secure: Z1lLeO5BF5CS4OfxJ8MMendtg3FbzZsdAJe/NcYRA2UNca/bmibRGO5as/F/1mgANTKJuzdy5y+udNU56FOyrNK+SU7Vb5btDjrfvgBjEiX0NrNXNR0TgyIXXdPqQq5J3qo8DrF0CoMbLU22Q0X0gMal5T8FLXArp68tcGF6icUwUUH0FtvLrOTMf+m7AoqJ7CycsI+nyqZeCe3LSe7I3yu97IEA40CYY1oi4zlss+acGDBLzCLwATHVCE9fZ23Ij+azJbjLyTgolf2AqoIBSYFCDYfeq+ujjfN2HewDp4fhUq0GYUmU7xzx7izTX8elo3fZfQYG9w+C5dYlyY3OMrwrNO6am2KQ9+a4mDYEehvrmFHOsj9juA6KLcE/tEjpMpmPxLq691uTP/+im1Is9R1YU+4etQE9jx/oW5Ck8H7TJ63w5EgGnDAYkz3nodcPeum7JaeVKpIVaAGPmseZ7Cg7KSAU48t6y5op3P1qS7WLtBWTHqc8yEoBqJ8ymBoUC0eyJE4zOvYrZIM5r4Xr3jrc2sih7LQXBkvr81edXZ1Olsy2D0IcCMZuaSZ1rc8mcDF8cCVi1QnQbFPS1Yc1YWJ1IgkT+jtRqTpA7zjZjc/CW/6M5FCRueruKlCf09yO4X1YBIxUc77SLv48JRLNpjdlGEV4BH3+W5DwO+u/4tU=
